import React,{useState} from 'react'
import SearchBar from '../components/SearchBar'
import Coins from '../components/Coins'
import CoinList from '../components/CoinList'
import Layout from '../components/Layout'

export default function Home({filteredCoins}) {

  const [search, setSearch] = useState('')

  // Filtrar pesquisas que sejam com letra minuscula
  const allCoins = filteredCoins.filter(coin => 
    coin.name.toLowerCase().includes(search.toLocaleLowerCase())
  )

  // Vai pegar a pesquisa que ta me minusculo
  // handleChange() e uma função que cria um novo estado, após a mudança do valor
  const handleChange = e => {
    e.preventDefault()

    setSearch(e.target.value.toLowerCase())
  }
  
  return (
    <Layout>
      {/* <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <div className='coin_app'>
        <SearchBar type='text' placeholder="Procurar" onChange={handleChange}/>
        <CoinList filteredCoins={allCoins}/>
      </div>
    </Layout>
  )
}

// Consultando a API e colocando a resposta na variavel/props filteredCoins
export const getServerSideProps = async() => {

  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=brl&order=market_cap_desc&per_page=10&page=1&sparkline=false')

  const filteredCoins = await res.json()

  return{
    props:{
      filteredCoins
    } 
  }
}